### PR TITLE
Add some more columns

### PR DESCRIPTION
**Pull request by bcolsen**
Here's some more columns.

It would be great if they could publish a list of these.

Has anyone tried asking?

### CODE REVIEW

**Comment by chatcannon** [comment]
@bcolsen Do you have any files you are willing to share that include these new data columns? It would be good to add them to the tests.

**Comment by chatcannon** [comment]
I followed your suggestion and sent them a message on their online contact form.

**Comment by chatcannon** [comment]
Here's the response I got from Bio-Logic.

> Dear Mr KERR,
>
> I'm sorry but we cannot supply to you the code detail from our MPR file.
>
> This is considered by confidential information's ...

I can only recommend that anyone considering purchasing a battery cycler choose a manufacturer who respects its customers better...

**Comment by bcolsen** [comment]
Yep. That's the easiest answer to give. 

It doesn't really hurt the company to open it.

**Pull request merged**
