### PR TITLE
[PR] Biologic file with duplicate columns

### LINKED ISSUE #25: Duplicate columns in the main data biologic
I have a files from a my new biologic that has duplicate columns. The columns have the same ID and data. As a result the file errors saying the dtype doesn't match the length of data.

This happens because the ordered dict only registers one of the columns.

Since neither a dictionary nor a numpy recarray can have the same keys this raises a problem.

I have a PR to fix this.

### PR DESCRIPTION
**Pull request by bcolsen**
I know this is a large change, but the data_dtype_dict seem made it much easier to implement. It's also a good way to keep the data out of the logic.

If any column is repeated, I append the column number to the name. This isn't overly elegant but it does assure uniqueness.

Fixes #25

### CODE REVIEW

**Comment by bcolsen** [comment]
Looks like I need to fix the flags.

I will put a test on this with a small test data file too.

**Comment by chatcannon** [comment]
Thanks, I was planning to tidy this up in a similar way myself but never got round to it.

**Comment by chatcannon** [comment]
I want to make a few tweaks to this but don't have the time right now.

If you could send me a test file (preferably also with the corresponding .mpt exported by EC-Lab) that would be helpful.

**Comment by bcolsen** [comment]
I'll make a simple EIS test file with loops next week. I'll use that to write some tests and I'll send it your way.

**Comment by chatcannon** [comment]
If you are adding a file to the repo it would be nice if you could try out git-lfs (see #18). When I first set up this repo, git-lfs wasn't supported by GitHub so I stored the files externally on figshare.com. I would need to check whether it would cause any compatibility problems for people who don't have git-lfs installed, though.

**Comment by chatcannon** [comment]
Alternatively just add a file to the discussion here and I can add it to figshare.

**Comment by chatcannon** [comment]
@bcolsen I have added the changes I wanted to make, do you have any comments?

Also, would you like to join in as a maintainer on the galvani project? Since I'm not actively using it any more, it would be good to have someone on board who has access to the EC-Lab software and instruments.

**Comment by bcolsen** [comment]
@chatcannon I like the cleanup! The comments about the flags are very helpful.

> Also, would you like to join in as a maintainer on the galvani project?

Yes, that sounds great. This is actually an important part of our current data analysis pipeline and I have access to 3 different Biologic units and some Arbin units as well.

Thank you posting this project. I know from experience that reading binary files without proper docs is tricky and these ones are particularly obscure.

I need to make some test files for this too.

**Comment by chatcannon** [comment]
OK, I will look up the docs on how to migrate a personal project to a group 
project and add other developers to the group.

**Pull request merged**
