### PR TITLE
improved parsing for PEIS files

### PR DESCRIPTION
**Pull request by bayesfactor**
I found some new column types and a new placement of the ole_timestamp for PEIS files

### CODE REVIEW

**Comment by chatcannon** [comment]
Thanks @bayesfactor and sorry for taking so long to get around to looking at this

**Comment by chatcannon** [comment]
@bayesfactor Do you have any data files with these extra columns that I could add to the tests?

**Comment by bayesfactor** [comment]
@chatcannon, the data files are proprietary to my company, so I can't share them unfortunately. A PEIS test should be sufficient to test.  Since you're interested, I figured out a few other columns from GEIS tests -- want me to add them?

**Comment by chatcannon** [comment]
Yes please.

Unfortunately I no longer directly work with battery cyclers so I'm not able to create files myself.

**Pull request merged**
